const fs=require('fs'),path=require('path'),Module=require('module'),assert=require('assert/strict'),ts=require('../web/node_modules/typescript');
const user={userId:'owner-a',email:'preview@example.invalid'},rows=[];let inserts=0,photoOperations=0;
function load(file,mocks){const filename=path.resolve(file),m=new Module(filename,module);m.paths=Module._nodeModulePaths(path.dirname(filename));const original=m.require.bind(m);m.require=id=>id in mocks?mocks[id]:original(id);m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);return m.exports;}
const model=load('web/app/model.ts',{});
const meal=model.mealSchema.parse({name:'Rice',date:'2026-10-02',time:'12:00',category:'Lunch',notes:'Measured fixture',calories:130,protein:3,carbs:28,fat:.3,fiber:.4,saturatedFat:null,unsaturatedFat:null,sugar:null,sodium:null,vitaminC:null,vitaminD:null,calcium:null,iron:null});
const client={from:()=>{const filters={};return{select(){return this;},eq(field,value){filters[field]=value;return this;},async maybeSingle(){return{data:rows.find(row=>Object.entries(filters).every(([key,value])=>row[key]===value))||null,error:null};},async insert(row){rows.push(row);inserts++;return{error:null};}};},storage:{from:()=>({upload:async()=>{photoOperations++;return{error:null};},remove:async()=>{photoOperations++;return{error:null};}})},auth:{signInWithPassword:async()=>({error:Error('incorrect password'),data:{user:null}})}};
const mocks={'../../chatgpt-auth':{getChatGPTUser:async()=>user},'../../../lib/supabase/server':{createClient:async()=>client},'../../model':model};
const api=load('web/app/api/meals/route.ts',mocks),privacy=load('web/app/api/privacy/route.ts',mocks);
function request(owner='owner-a',origin='https://fuel-journal.vercel.app'){const body=new FormData();body.set('meal',JSON.stringify(meal));body.set('clientId','a0f48080-867d-4b61-a51f-8e1e8edca7fd');body.set('owner',owner);return new Request('https://fuel-journal.vercel.app/api/meals',{method:'POST',headers:{origin},body});}
(async()=>{assert.equal((await api.POST(request('owner-b'))).status,403,'Outbox from another account must not sync into the current account');assert.equal(inserts,0);assert.equal((await api.POST(request('owner-a','https://other.example'))).status,403);assert.equal((await api.POST(request())).status,201);assert.equal((await api.POST(request())).status,200);assert.equal(inserts,1,'Lost responses and retries must not duplicate meals');assert.equal(rows[0].owner,user.userId);
 const privacyRequest=body=>new Request('https://fuel-journal.vercel.app/api/privacy',{method:'POST',headers:{origin:'https://fuel-journal.vercel.app','Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal((await privacy.POST(privacyRequest({action:'account',confirm:'NO',password:'wrong-password'}))).status,400);assert.equal((await privacy.POST(privacyRequest({action:'account',confirm:'DELETE',password:'wrong-password'}))).status,403);assert.equal(photoOperations,0,'Failed account confirmation/password must not remove photos');
 console.log('PASS: cross-account queued uploads rejected, origin checks, duplicate-safe save and no deletion before typed confirmation/password validation. All auth/storage operations mocked.');
})();
