'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {createClient} from '../../lib/supabase/client';
export default function Login(){
 const [signup,setSignup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(new URLSearchParams(location.search).get('confirmation')==='failed')setMessage('The email link could not be verified. Request another link or sign in again.');},[]);
 async function recover(){if(!email.trim()){setMessage('Enter your email above, then request a recovery link.');return;}setBusy(true);document.cookie='fuel-password-recovery=1; Path=/; SameSite=Lax; Max-Age=1800'+(location.protocol==='https:'?'; Secure':'');try{const {error}=await createClient().auth.resetPasswordForEmail(email.trim(),{redirectTo:location.origin+'/auth/callback'});if(error)throw error;setMessage('If this email has an account, a recovery link has been requested. Check spam too. Open it in this same browser; delivery is subject to email-service limits.');}catch(e){document.cookie='fuel-password-recovery=; Path=/; Max-Age=0';setMessage((e as Error).message);}finally{setBusy(false);}}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const client=createClient();const result=signup?await client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/auth/callback'}}):await client.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(result.data.session)location.replace('/');else setMessage('Check your email to confirm your account, then sign in here.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <main className="login-page"><a className="brand" href="/welcome">fuel<span>✳</span></a><div className="card login-card"><span className="eyebrow">YOUR PRIVATE MEAL JOURNAL</span><h1>{signup?'Make room for progress':'Welcome back'}<span>.</span></h1><p className="login-copy">Your meals. Your goals. Together on every device.</p><form onSubmit={submit}><label>Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required minLength={8} type="password" autoComplete={signup?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'One moment…':signup?'Create my account':'Open my journal'}</button></form>{message&&<p className="notice" role="status">{message}</p>}<button className="text-btn" onClick={()=>{setSignup(!signup);setMessage('');}}>{signup?'Already have an account? Sign in':'New here? Create a free account'}</button>{!signup&&<button className="text-btn" disabled={busy} onClick={recover}>Forgot password?</button>}<a className="text-btn" href="/welcome">Discover Fuel</a></div></main>;
}
