'use client';
import {useEffect,useState} from 'react';
import {Meal} from './model';
import {nativeInfo,nativeMessage} from './native';
import {LabelProduct,labelMeal} from './food-label';
export function BarcodeLookup({onMeal}:{onMeal:(meal:Meal)=>void}){
 const [expanded,setExpanded]=useState(false);
 const [code,setCode]=useState(''),[product,setProduct]=useState<LabelProduct|null>(null),[amount,setAmount]=useState('100'),[fiber,setFiber]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function lookup(value=code){setBusy(true);setError('');setProduct(null);try{const response=await fetch('/api/foods?barcode='+encodeURIComponent(value));const data=await response.json();if(!response.ok)throw Error(data.error);setProduct(data.product);setFiber('');}catch(e){setError(e instanceof Error?e.message:'Lookup failed. Try again.');}finally{setBusy(false);}}
 useEffect(()=>{const scanned=(event:Event)=>{const value=(event as CustomEvent).detail?.code;if(typeof value==='string'&&/^\d{8,14}$/.test(value)){setExpanded(true);setCode(value);delete (window as any).__fuelBarcode;void lookup(value);}};window.addEventListener('fuel-barcode',scanned);const pending=(window as any).__fuelBarcode;if(pending)scanned(new CustomEvent('fuel-barcode',{detail:{code:pending}}));return()=>window.removeEventListener('fuel-barcode',scanned);},[]);
 return <details className="label-lookup" open={expanded} onToggle={e=>setExpanded(e.currentTarget.open)}><summary>Log a packaged food</summary><p>Scan in the updated Android app, or enter the barcode number. Check the result against your package.</p><div className="tool-actions"><label>Barcode<input aria-label="Product barcode" inputMode="numeric" maxLength={14} value={code} onChange={e=>{setCode(e.target.value.replace(/\D/g,''));setProduct(null);}}/></label><button className="secondary" disabled={busy||code.length<8} onClick={()=>lookup()}>{busy?'Looking up…':'Find product'}</button><button className="secondary" disabled={busy} onClick={()=>{if(!nativeInfo()||nativeInfo()!.versionCode<5||!nativeMessage({type:'fuel-barcode'}))setError('Camera scanning needs Fuel 0.4 or newer on Android. You can enter the digits above on any device.');}}>Scan barcode</button></div>{error&&<p className="notice error" role="alert">{error}</p>}{product&&<div className="label-result"><h3>{product.name}</h3><p>{product.nutrients.calories} kcal per 100{product.basis} · community label data</p><label>Amount eaten ({product.basis})<input type="number" min="1" max="2000" value={amount} onChange={e=>setAmount(e.target.value)}/></label>{product.nutrients.fiber===null&&<label>Fibre for your serving (g) · missing from database<input type="number" min="0" value={fiber} onChange={e=>setFiber(e.target.value)}/></label>}<button className="primary" onClick={()=>{try{if(product.nutrients.fiber===null&&fiber==='')throw Error('Enter the fibre from your label, including 0 if the label states zero.');onMeal(labelMeal(product,Number(amount),Number(fiber)));}catch(e){setError((e as Error).message);}}}>Review this serving</button><a href={product.url} target="_blank" rel="noreferrer">Source: Open Food Facts · ODbL</a></div>}<small>Open Food Facts is a community database. Products and recipes can change; your package label takes priority.</small></details>;
}
