'use client';
import {useRef,useState} from 'react';
import {EstimatedFood} from './analysis';
import {nutrientKeys} from './model';
import {correctedFood,measuredPortion,scaledFood} from './food-corrections';
const labels:Record<string,string>={calories:'Calories',protein:'Protein',carbs:'Carbs',fat:'Fat',fiber:'Fiber',saturatedFat:'Saturated fat',unsaturatedFat:'Unsaturated fat',sugar:'Sugar',sodium:'Sodium',vitaminC:'Vitamin C',vitaminD:'Vitamin D',calcium:'Calcium',iron:'Iron'};
const unit=(key:string)=>key==='calories'?'kcal':key==='vitaminD'?'µg':['sodium','vitaminC','calcium','iron'].includes(key)?'mg':'g';
const valuesOf=(food:EstimatedFood)=>Object.fromEntries(nutrientKeys.map(key=>[key,food[key]===null?'':String(food[key])]));
export function FoodEditor({food,scale,disabled,onApply,onDirty}:{food:EstimatedFood;scale:number;disabled:boolean;onApply:(food:EstimatedFood)=>void;onDirty:()=>void}){
 const initial=scaledFood(food,scale),measurement=measuredPortion(initial.portion);
 const [values,setValues]=useState(()=>valuesOf(initial)),[portion,setPortion]=useState(initial.portion),[name,setName]=useState(food.name),[per100,setPer100]=useState(false),[error,setError]=useState('');
 const lastMeasured=useRef(measurement);
 function changePortion(next:string){const before=lastMeasured.current,after=measuredPortion(next);if(!per100&&before&&after&&before.unit===after.unit){setValues(current=>Object.fromEntries(nutrientKeys.map(key=>[key,current[key]===''?'':String(Math.round(Number(current[key])*after.amount/before.amount*10)/10)])));}if(after)lastMeasured.current=after;setPortion(next);}
 function apply(){try{const corrected=correctedFood({...food,name},values,portion,per100);onApply(corrected);setError('');}catch(e){setError(e&&typeof e==='object'&&'issues' in e?String((e as {issues:{message:string}[]}).issues[0]?.message):e instanceof Error?e.message:'Check the nutrition values.');}}
 return <details className="food-editor"><summary>Edit amount or package macros</summary><p>Values are for this food only. Changing a measured weight scales the nutrients. Replace any value with your package label, then apply.</p><fieldset disabled={disabled} onChange={onDirty}><label className="field-block">Food name<input value={name} maxLength={120} onChange={e=>setName(e.target.value)}/></label><label className="field-block">Amount eaten<input aria-label={`${food.name} amount eaten`} value={portion} maxLength={180} placeholder="200g" onChange={e=>changePortion(e.target.value)}/></label>{!measurement&&<small>Use a measured amount such as 200g for automatic scaling.</small>}<label className="field-block">Nutrition values are for<select value={per100?'100':'portion'} onChange={e=>{setPer100(e.target.value==='100');setValues(Object.fromEntries(nutrientKeys.map(key=>[key,''])));}}><option value="portion">The amount eaten above</option><option value="100">Per 100g / 100ml on the label</option></select></label><div className="form-grid">{nutrientKeys.slice(0,5).map(key=><label key={key}>{labels[key]} ({unit(key)})<input aria-label={`${food.name} ${labels[key]}`} type="number" min={0} step="0.1" value={values[key]} onChange={e=>setValues(current=>({...current,[key]:e.target.value}))}/></label>)}</div><details className="more-nutrients"><summary>Optional label nutrients</summary><div className="form-grid">{nutrientKeys.slice(5).map(key=><label key={key}>{labels[key]} ({unit(key)})<input type="number" min={0} step="0.1" value={values[key]} onChange={e=>setValues(current=>({...current,[key]:e.target.value}))}/></label>)}</div></details><button type="button" className="secondary" onClick={apply}>Apply food corrections</button></fieldset>{error&&<p role="alert" className="notice error">{error}</p>}</details>;
}
