import {Meal,Goals,mealSchema} from './model';
type Snapshot={owner:string;meals:Meal[];goals:Goals;updated:number};
type Pending={id:string;owner:string;meal:Meal;photo?:Blob;created:number};
const activeKey='fuel-local-owner';
function openDB():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('fuel-private-journal',2);request.onupgradeneeded=()=>{const db=request.result;for(const [name,keyPath] of [['snapshots','owner'],['outbox','id'],['drafts','owner']])if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error('Device storage is unavailable. Your meal has not been saved.'));request.onblocked=()=>reject(new Error('Close other Fuel tabs and retry to update device storage.'));});}
async function store<T>(name:string,mode:IDBTransactionMode,action:(store:IDBObjectStore)=>IDBRequest):Promise<T>{const db=await openDB();try{return await new Promise<T>((resolve,reject)=>{const transaction=db.transaction(name,mode),request=action(transaction.objectStore(name));transaction.oncomplete=()=>resolve(request.result as T);transaction.onerror=()=>reject(transaction.error||new Error('Device storage failed'));transaction.onabort=()=>reject(transaction.error||new Error('Device storage was interrupted'));});}finally{db.close();}}
export function rememberedOwner(){try{return localStorage.getItem(activeKey);}catch{return null;}}
export async function readSnapshot(owner:string){return store<Snapshot|undefined>('snapshots','readonly',s=>s.get(owner));}
export async function writeSnapshot(owner:string,meals:Meal[],goals:Goals){await store('snapshots','readwrite',s=>s.put({owner,meals:meals.filter(m=>!m.demo).map(({photo,...m})=>({...m,photo:photo?.startsWith('blob:')?undefined:photo})),goals,updated:Date.now()}));localStorage.setItem(activeKey,owner);}
export async function pendingMeals(owner:string){return (await store<Pending[]>('outbox','readonly',s=>s.getAll())).filter(row=>row.owner===owner);}
async function send(entry:Pending){const body=new FormData();body.set('meal',JSON.stringify(mealSchema.parse(entry.meal)));body.set('clientId',entry.id);body.set('owner',entry.owner);if(entry.photo)body.set('photo',entry.photo,'meal.jpg');let response:Response;try{response=await fetch('/api/meals',{method:'POST',body});}catch{throw new Error('offline');}if(response.status>=500)throw new Error('offline');const data=await response.json().catch(()=>{throw new Error(response.ok?'offline':'Meal could not be saved. Please retry.');});if(!response.ok)throw new Error(data.error||'Meal could not be saved');const parsed=mealSchema.safeParse(data.meal);if(!parsed.success||data.meal?.id!==entry.id)throw new Error('offline');return {...parsed.data,id:entry.id,photo:typeof data.meal.photo==='string'?data.meal.photo:undefined} as Meal;}
export async function saveMeal(owner:string,meal:zMeal,photo?:File){const entry:Pending={id:crypto.randomUUID(),owner,meal:{...mealSchema.parse(meal),id:'',pending:true},photo:photo?new Blob([await photo.arrayBuffer()],{type:photo.type}):undefined,created:Date.now()};entry.meal.id=entry.id;await store('outbox','readwrite',s=>s.put(entry));if(navigator.onLine){try{const saved=await send(entry);await store('outbox','readwrite',s=>s.delete(entry.id));return saved;}catch(error){if(!(error instanceof Error)||error.message!=='offline'){await store('outbox','readwrite',s=>s.delete(entry.id));throw error;}}}return entry.meal;}
type zMeal=ReturnType<typeof mealSchema.parse>;
const syncing=new Map<string,Promise<Meal[]>>();
export function syncMeals(owner:string){const existing=syncing.get(owner);if(existing)return existing;const task=(async()=>{const saved:Meal[]=[];for(const entry of await pendingMeals(owner)){try{saved.push(await send(entry));await store('outbox','readwrite',s=>s.delete(entry.id));}catch(error){if(error instanceof Error&&error.message==='offline')break;throw error;}}return saved;})().finally(()=>{syncing.delete(owner);});syncing.set(owner,task);return task;}
export async function removePending(owner:string,id:string){const entries=await pendingMeals(owner);if(entries.some(e=>e.id===id))await store('outbox','readwrite',s=>s.delete(id));}
export type MealDraft={owner:string;form:Record<string,unknown>;foods:unknown[];scales:number[];photo?:Blob;details:string;extras:string;estimateNote:string;description?:string;textDirty?:boolean;corrections?:number[];analysisKind?:'photo'|'text';updated:number};
export async function readDraft(owner:string){return store<MealDraft|undefined>('drafts','readonly',s=>s.get(owner));}
const draftWrites=new Map<string,Promise<unknown>>();
function draftTask(owner:string,action:()=>Promise<void>){const run=(draftWrites.get(owner)||Promise.resolve()).catch(()=>{}).then(action);draftWrites.set(owner,run);void run.finally(()=>{if(draftWrites.get(owner)===run)draftWrites.delete(owner);}).catch(()=>{});return run;}
export function writeDraft(draft:MealDraft){return draftTask(draft.owner,async()=>{const photo=draft.photo?new Blob([await draft.photo.arrayBuffer()],{type:draft.photo.type}):undefined;await store('drafts','readwrite',s=>s.put({...draft,photo}));});}
export function clearDraft(owner:string){return draftTask(owner,async()=>{await store('drafts','readwrite',s=>s.delete(owner));});}
export async function clearLocalJournal(owner?:string){const current=owner||rememberedOwner();try{if(current){await store('snapshots','readwrite',s=>s.delete(current));await clearDraft(current);for(const row of await pendingMeals(current))await store('outbox','readwrite',s=>s.delete(row.id));}}finally{localStorage.removeItem(activeKey);}}
