import {Meal,Goals,mealSchema} from './model';
type Snapshot={owner:string;meals:Meal[];goals:Goals;updated:number};
type Pending={id:string;owner:string;meal:Meal;photo?:Blob;created:number};
const activeKey='fuel-local-owner';
function openDB():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('fuel-private-journal',1);request.onupgradeneeded=()=>{const db=request.result;db.createObjectStore('snapshots',{keyPath:'owner'});db.createObjectStore('outbox',{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error('Device storage is unavailable. Your meal has not been saved.'));});}
async function store<T>(name:string,mode:IDBTransactionMode,action:(store:IDBObjectStore)=>IDBRequest):Promise<T>{const db=await openDB();try{return await new Promise<T>((resolve,reject)=>{const transaction=db.transaction(name,mode),request=action(transaction.objectStore(name));transaction.oncomplete=()=>resolve(request.result as T);transaction.onerror=()=>reject(transaction.error||new Error('Device storage failed'));transaction.onabort=()=>reject(transaction.error||new Error('Device storage was interrupted'));});}finally{db.close();}}
export function rememberedOwner(){try{return localStorage.getItem(activeKey);}catch{return null;}}
export async function readSnapshot(owner:string){return store<Snapshot|undefined>('snapshots','readonly',s=>s.get(owner));}
export async function writeSnapshot(owner:string,meals:Meal[],goals:Goals){await store('snapshots','readwrite',s=>s.put({owner,meals:meals.filter(m=>!m.demo).map(({photo,...m})=>({...m,photo:photo?.startsWith('blob:')?undefined:photo})),goals,updated:Date.now()}));localStorage.setItem(activeKey,owner);}
export async function pendingMeals(owner:string){return (await store<Pending[]>('outbox','readonly',s=>s.getAll())).filter(row=>row.owner===owner);}
async function send(entry:Pending){const body=new FormData();body.set('meal',JSON.stringify(mealSchema.parse(entry.meal)));body.set('clientId',entry.id);body.set('owner',entry.owner);if(entry.photo)body.set('photo',entry.photo,'meal.jpg');let response:Response;try{response=await fetch('/api/meals',{method:'POST',body});}catch{throw new Error('offline');}if(response.status>=500)throw new Error('offline');const data=await response.json().catch(()=>{throw new Error(response.ok?'offline':'Meal could not be saved. Please retry.');});if(!response.ok)throw new Error(data.error||'Meal could not be saved');return data.meal as Meal;}
export async function saveMeal(owner:string,meal:zMeal,photo?:File){const entry:Pending={id:crypto.randomUUID(),owner,meal:{...meal,id:'',pending:true},photo,created:Date.now()};entry.meal.id=entry.id;if(navigator.onLine){try{return await send(entry);}catch(error){if(!(error instanceof Error)||error.message!=='offline')throw error;}}await store('outbox','readwrite',s=>s.put(entry));return entry.meal;}
type zMeal=ReturnType<typeof mealSchema.parse>;
const syncing=new Map<string,Promise<Meal[]>>();
export function syncMeals(owner:string){const existing=syncing.get(owner);if(existing)return existing;const task=(async()=>{const saved:Meal[]=[];for(const entry of await pendingMeals(owner)){try{saved.push(await send(entry));await store('outbox','readwrite',s=>s.delete(entry.id));}catch(error){if(error instanceof Error&&error.message==='offline')break;throw error;}}return saved;})().finally(()=>{syncing.delete(owner);});syncing.set(owner,task);return task;}
export async function removePending(owner:string,id:string){const entries=await pendingMeals(owner);if(entries.some(e=>e.id===id))await store('outbox','readwrite',s=>s.delete(id));}
export async function clearLocalJournal(owner?:string){const current=owner||rememberedOwner();try{if(current){await store('snapshots','readwrite',s=>s.delete(current));for(const row of await pendingMeals(current))await store('outbox','readwrite',s=>s.delete(row.id));}}finally{localStorage.removeItem(activeKey);}}
