'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,Upload,Sparkles,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {dateKey,nutrientKeys,mealSchema,Meal} from './model';
import {totalFoods,EstimatedFood,foodSchema} from './analysis';
import {FoodEditor} from './food-editor';
import {keepCorrections} from './food-corrections';
import {installPhotoReceiver,requestPhoto} from './native-photo';
import {saveMeal,readDraft,writeDraft,clearDraft} from './local-journal';
const labels:Record<string,string>={calories:'Calories',protein:'Protein',carbs:'Carbs',fat:'Total fat',fiber:'Fiber',saturatedFat:'Saturated fat',unsaturatedFat:'Unsaturated fat',sugar:'Sugar',sodium:'Sodium',vitaminC:'Vitamin C',vitaminD:'Vitamin D',calcium:'Calcium',iron:'Iron'};
const unit=(k:string)=>k==='calories'?'kcal':k==='vitaminD'?'µg':['sodium','vitaminC','calcium','iron'].includes(k)?'mg':'g';
const fresh=()=>({name:'',date:dateKey(),time:new Date().toTimeString().slice(0,5),category:'Lunch',notes:'',...Object.fromEntries(nutrientKeys.map(k=>[k,'']))});
async function request(url:string,body:FormData){const r=await fetch(url,{method:'POST',body,signal:AbortSignal.timeout(60000)});const data=await r.json().catch(()=>{throw Error('The server did not respond clearly. Your photo is kept; retry.');});if(!r.ok)throw new Error(data.error||'Please try again.');return data;}
export function MealForm({open,close,onSaved,onPhotoOpen,owner,retainPhotos,initialMeal,onRecipe}:{open:boolean;close:()=>void;onSaved:(m:Meal)=>void;onPhotoOpen?:()=>void;owner:string;retainPhotos:boolean;initialMeal?:Meal|null;onRecipe?:(meal:Meal)=>void}){
 const [reviewed,setReviewed]=useState(false),[pickerPending,setPickerPending]=useState(false);
 const pickerTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [stage,setStage]=useState('capture'),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[analyzing,setAnalyzing]=useState(false),[estimateNote,setEstimateNote]=useState('');
 const [form,setForm]=useState<any>(fresh),[foods,setFoods]=useState<EstimatedFood[]>([]),[scales,setScales]=useState<number[]>([]),[details,setDetails]=useState(''),[extras,setExtras]=useState('');
 const analysisLock=useRef(false),selectionLock=useRef(false),draftPaused=useRef(false);
 const [draftStatus,setDraftStatus]=useState('');
 const [description,setDescription]=useState(''),[corrections,setCorrections]=useState<number[]>([]),[editRevision,setEditRevision]=useState(0);
 const [dirtyFoods,setDirtyFoods]=useState<number[]>([]);
 const [textDirty,setTextDirty]=useState(false);
 const [analysisKind,setAnalysisKind]=useState<'photo'|'text'>('photo');
 const cameraInput=useRef<HTMLInputElement>(null),galleryInput=useRef<HTMLInputElement>(null);
 const receiveRef=useRef<(file:File)=>void>(()=>{});
 receiveRef.current=(photo)=>{setPickerPending(false);if(pickerTimer.current)clearTimeout(pickerTimer.current);if(!analysisLock.current){onPhotoOpen?.();selectFile(photo);}};
 useEffect(()=>{if(open)draftPaused.current=false;},[open]);
 useEffect(()=>{if(open&&initialMeal){setStage('confirm');setFile(null);setPreview('');setForm({...initialMeal,date:dateKey(),time:new Date().toTimeString().slice(0,5),...Object.fromEntries(nutrientKeys.map(k=>[k,initialMeal[k]===null?'':String(initialMeal[k])]))});setFoods([]);setReviewed(true);}},[open,initialMeal]);
 async function persistDraft(){if(stage!=='confirm'||draftPaused.current)return;await writeDraft({owner,form,foods,scales,photo:file||undefined,details,extras,estimateNote,description,corrections,analysisKind,textDirty,updated:Date.now()});setDraftStatus('Draft saved on this device');}
 async function keepAndClose(){if(dirtyFoods.length){setError('Apply your food corrections before closing so they are kept in the draft.');return;}try{await persistDraft();reset();close();}catch(e){console.error('Draft storage failed',{name:e instanceof Error?e.name:'Unknown'});setError('Draft could not be saved. Keep this form open or save the meal before closing.');}}
 useEffect(()=>{if(!open||initialMeal||stage!=='capture'||selectionLock.current)return;let live=true;readDraft(owner).then(draft=>{if(!live||!draft)return;setTextDirty(draft.textDirty||false);setDescription(draft.description||'');setCorrections(draft.corrections||[]);setAnalysisKind(draft.analysisKind||'photo');setForm(draft.form);setFoods(draft.foods.map(f=>foodSchema.parse(f)));setScales(draft.scales);setDetails(draft.details);setExtras(draft.extras);setEstimateNote(draft.estimateNote);setReviewed(false);setStage('confirm');if(draft.photo){const restored=new File([draft.photo],'meal.jpg',{type:draft.photo.type});setFile(restored);setPreview(URL.createObjectURL(restored));}setDraftStatus('Recovered your unfinished meal. Review before saving.');}).catch(()=>{});return()=>{live=false;};},[open,owner,initialMeal]);
 useEffect(()=>{if(!open||stage!=='confirm')return;const timer=setTimeout(()=>{persistDraft().catch(()=>setDraftStatus('Draft storage unavailable. Keep this form open.'));},600);return()=>clearTimeout(timer);},[open,stage,form,foods,scales,file,details,extras,estimateNote,description,corrections,analysisKind,textDirty]);
 useEffect(()=>{const started=()=>{if(pickerTimer.current)clearTimeout(pickerTimer.current);setPickerPending(false);};window.addEventListener('fuel-picker-started',started);return()=>{window.removeEventListener('fuel-picker-started',started);if(pickerTimer.current)clearTimeout(pickerTimer.current);};},[]);
 useEffect(()=>installPhotoReceiver(photo=>receiveRef.current(photo),message=>setError(message)),[]);
 useEffect(()=>{const back=(event:Event)=>{if(open){event.preventDefault();if(!busy&&!analyzing)void keepAndClose();}};window.addEventListener('fuel-back',back);return ()=>window.removeEventListener('fuel-back',back);},[open,busy,analyzing,stage,form,file,foods,scales,details,extras,estimateNote,dirtyFoods,description,corrections,analysisKind,textDirty]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const update=(key:string,value:string)=>setForm((f:any)=>({...f,[key]:value}));
 function reset(){draftPaused.current=true;setDraftStatus('');setDirtyFoods([]);setTextDirty(false);setDescription('');setCorrections([]);setAnalysisKind('photo');setReviewed(false);setPickerPending(false);setStage('capture');setFile(null);setPreview('');setForm(fresh());setFoods([]);setScales([]);setEstimateNote('');setDetails('');setExtras('');setError('');}
 function applyFoods(rows:EstimatedFood[],multipliers:number[]){const sums=totalFoods(rows,multipliers);const notes=rows.map((f,i)=>({food:f,scale:multipliers[i]})).filter(v=>v.scale>0).map(v=>`${v.food.name}: ${v.food.portion} × ${v.scale}`).join('; ');setForm((f:any)=>({...f,notes:('Meal nutrition; portions reviewed: '+notes).slice(0,1000),...Object.fromEntries(nutrientKeys.map(k=>[k,sums[k]===null?'':String(sums[k])]))}));}
 function changeScale(index:number,value:string){setReviewed(false);if(dirtyFoods.includes(index)){setError('Apply this food’s corrections before changing its multiplier.');return;}if(value==='')return;const n=Number(value);if(!Number.isFinite(n)||n<0||n>10)return;const next=scales.map((s,i)=>i===index?n:s);setScales(next);setEditRevision(v=>v+1);applyFoods(foods,next);}
 function applyCorrection(index:number,food:EstimatedFood){setDirtyFoods(current=>current.filter(i=>i!==index));const rows=foods.map((row,i)=>i===index?food:row),next=scales.map((scale,i)=>i===index?1:scale);setFoods(rows);setScales(next);setCorrections(current=>[...new Set([...current,index])]);setReviewed(false);setEditRevision(v=>v+1);applyFoods(rows,next);}
 async function selectFile(f?:File){if(!f||analysisLock.current||selectionLock.current)return;if(f.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type)){setError('Choose a JPG, PNG or WebP image under 5 MB.');return;}draftPaused.current=false;selectionLock.current=true;setBusy(true);try{f=new File([await f.arrayBuffer()],f.name,{type:f.type});}catch{setError('This photo can no longer be read. Choose it again so Fuel can keep a safe device copy.');return;}finally{selectionLock.current=false;setBusy(false);}setDirtyFoods([]);setTextDirty(false);setDescription('');setCorrections([]);setAnalysisKind('photo');setFile(f);setPreview(URL.createObjectURL(f));setStage('confirm');setForm(fresh());setFoods([]);setScales([]);setEstimateNote('');setDetails('');setExtras('');setReviewed(false);if(navigator.onLine)void analyze(f,'');else setError('Photo captured on this device. AI analysis needs internet; enter label values now or retry analysis after reconnecting.');}
 function startText(){draftPaused.current=false;setFile(null);setPreview('');setForm(fresh());setFoods([]);setScales([]);setCorrections([]);setDirtyFoods([]);setDescription('');setDetails('');setExtras('');setEstimateNote('');setReviewed(false);setTextDirty(false);setAnalysisKind('text');setStage('confirm');}
 function choosePhoto(camera:boolean){setError('');try{if(requestPhoto(camera)){setPickerPending(true);pickerTimer.current=setTimeout(()=>{setPickerPending(false);setError('Android did not acknowledge the photo picker. Try Camera / Photos below the app header. Check your installed version in Settings → App & updates.');},8000);}else{const input=camera?cameraInput.current:galleryInput.current;if(input){input.value='';input.click();}}}catch{setPickerPending(false);setError('Photo picker could not open. Refresh the app or check Android camera permissions.');}}

 async function analyze(selected:File|null=file,context?:string){
  if(analysisLock.current)return;if(dirtyFoods.length&&context!==''){setError('Apply each food correction before requesting another estimate.');return;}if(!selected&&description.trim().length<3){setError('Write the foods and amounts you ate first.');return;}if(!navigator.onLine){setError('Connect to the internet to estimate your meal. Your form stays here.');return;}setReviewed(false);analysisLock.current=true;setAnalyzing(true);setError('');
  try{const body=new FormData();if(selected)body.set('photo',selected);else body.set('description',description.trim());const preserve=context!==''&&!textDirty;const current=(preserve?foods:[]).map((f,i)=>({food:f.name,portion:f.portion,multiplier:scales[i],appliedNutrition:corrections.includes(i)?f:undefined})).filter(f=>f.multiplier>0);body.set('context',context??JSON.stringify({correctedCompleteList:current.length?current:undefined,portionCorrections:details,additionalFoods:extras}));body.set('goal',String(document.querySelector('.chip')?.textContent||'Maintain'));const r=await request('/api/analyze',body),e=r.estimate;const rows=keepCorrections(e.foods,preserve?foods:[],scales,preserve?corrections:[]);setFoods(rows);setScales(rows.map(()=>1));setCorrections(rows.map((row:EstimatedFood,i:number)=>preserve&&foods.some((prior,j)=>corrections.includes(j)&&prior.name.trim().toLowerCase()===row.name.trim().toLowerCase())?i:-1).filter((i:number)=>i>=0));setEditRevision(v=>v+1);setTextDirty(false);setAnalysisKind(selected?'photo':'text');setForm((f:any)=>({...f,name:e.name}));applyFoods(rows,rows.map(()=>1));setEstimateNote(e.uncertainty+' '+e.suggestion);setExtras('');setDetails('');}
  catch(e){setError(e instanceof Error&&e.name==='TimeoutError'?'Analysis took too long. Your photo is kept; retry or add measured details.':(e as Error).message);}finally{analysisLock.current=false;setAnalyzing(false);}
 }
 async function save(e:React.FormEvent){e.preventDefault();setError('');if(dirtyFoods.length){setError('Tap Apply food corrections before saving.');return;}if(!file&&description.trim()&&(textDirty||!foods.length)){setError('Calculate macros from your updated food description before saving.');return;}const valid=mealSchema.safeParse({...form,...Object.fromEntries(nutrientKeys.map(k=>[k,form[k]===''?(nutrientKeys.indexOf(k)<5?NaN:null):Number(form[k])]))});if(!valid.success){setError(valid.error.issues[0].message);return;}if(foods.length&&(details.trim()||extras.trim())){setError('Apply your food corrections and extras before saving.');return;}if(foods.length&&!reviewed){setError('Confirm that you reviewed the detected foods, portions and hidden ingredients.');return;}setBusy(true);try{const meal=await saveMeal(owner,valid.data,retainPhotos&&file?file:undefined);draftPaused.current=true;await clearDraft(owner).catch(()=>{});onSaved(meal);reset();close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function saveRecipe(){if(dirtyFoods.length){setError('Apply food corrections before saving a recipe.');return;}if(!file&&description.trim()&&(textDirty||!foods.length)){setError('Calculate the updated description before saving a recipe.');return;}if(foods.length&&(details.trim()||extras.trim())){setError('Apply food corrections before saving a recipe.');return;}if(foods.length&&!reviewed){setError('Review and confirm the photo estimate before saving a recipe.');return;}const parsed=mealSchema.safeParse({...form,...Object.fromEntries(nutrientKeys.map(k=>[k,form[k]===''?(nutrientKeys.indexOf(k)<5?NaN:null):Number(form[k])]))});if(!parsed.success){setError(parsed.error.issues[0].message);return;}onRecipe?.({...parsed.data,id:crypto.randomUUID()});}
 const locked=busy||analyzing;
 return <Dialog open={open} onOpenChange={v=>{if(!locked&&!v)void keepAndClose();}}><DialogContent className="fuel-dialog"><DialogTitle>{stage==='capture'?'A little snap. A clearer picture.':'Review your plate'}</DialogTitle><DialogDescription>{stage==='capture'?'Photograph your meal or describe the foods and amounts. We’ll fill in the macros.':'Confirm the food and portions before saving. Photo estimates cannot measure hidden ingredients.'}</DialogDescription>
 {draftStatus&&<p className="fine-print" role="status">{draftStatus}</p>}{error&&<div role="alert" className="notice error">{error}</div>}{pickerPending&&<div className="notice" role="status">Opening Android’s photo picker…</div>}
 {stage==='capture'?<><div className="capture-area"><Camera size={45}/><h3>What’s on your plate?</h3><p>Use a clear, well-lit photo of your own plate. Add serving weights and cooking oils during review.</p><button type="button" className="primary file-label" disabled={locked||pickerPending} onClick={()=>choosePhoto(true)}><Camera size={18}/> Take a photo</button><button type="button" className="secondary file-label" disabled={locked||pickerPending} onClick={()=>choosePhoto(false)}><Upload size={18}/> Choose a photo</button><input ref={cameraInput} hidden type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={locked} onChange={e=>selectFile(e.target.files?.[0])}/><input ref={galleryInput} hidden type="file" accept="image/jpeg,image/png,image/webp" disabled={locked} onChange={e=>selectFile(e.target.files?.[0])}/><small>JPG, PNG or WebP · up to 5 MB<br/>Photos go to Google Gemini for analysis. On its free tier, Google may review and use submissions to improve its products. Avoid personal or sensitive information.</small></div><button type="button" className="secondary center" onClick={startText}>Type foods & amounts</button></>:<form onSubmit={save}>
 {!file&&<div className="analysis-box"><label className="field-block">What did you eat?<textarea aria-label="Foods and amounts" maxLength={3000} rows={4} value={description} disabled={locked} placeholder="e.g. 200g paneer, 150g cooked rice and 1 tsp oil. Paneer packet: 25g protein per 100g." onChange={e=>{setDescription(e.target.value);setTextDirty(true);setReviewed(false);}}/></label><button type="button" className="primary" disabled={locked||description.trim().length<3} onClick={()=>analyze(null)}><Sparkles size={17}/>{analyzing?'Calculating…':'Calculate macros from foods'}</button><small>Include grams, pieces or serving sizes, raw/cooked details, oil and package values when available. Fuel estimates the nutrients; you can correct them below. Descriptions go to Google Gemini on its free tier; avoid sensitive details.</small></div>}
 {preview&&<img className="form-photo" src={preview} alt="Your selected meal"/>}{analyzing&&<div className="analysis-progress" role="status"><Sparkles size={19}/><div><strong>Reading your plate…</strong><p>Using your food details to calculate estimated macros.</p></div></div>}
 {foods.length>0&&<section className="food-review"><div className="section-head"><h3>{analysisKind==='text'?'Your ingredients':'Detected foods'}</h3><span className="muted">ESTIMATED PORTIONS</span></div><p>Adjust each portion multiplier: 0 removes it, 0.5 is half, 2 is double. Totals update instantly.</p>{foods.map((food,i)=><div className="food-review-item" key={i}><div className="food-review-row"><div><strong>{food.name}</strong><small>{food.portion}</small><span>{Math.round(food.calories*scales[i])} kcal · {Math.round(food.protein*scales[i]*10)/10}g protein</span></div><label>Portion ×<input aria-label={`${food.name} portion multiplier`} type="number" min={0} max={10} step="0.25" value={scales[i]} disabled={locked} onChange={e=>changeScale(i,e.target.value)}/></label></div>{corrections.includes(i)&&<small className="correction-status">Your corrected values applied</small>}<FoodEditor key={`${i}-${JSON.stringify(food)}-${scales[i]}`} food={food} scale={scales[i]} disabled={locked} onDirty={()=>{setReviewed(false);setDirtyFoods(current=>[...new Set([...current,i])]);}} onApply={value=>applyCorrection(i,value)}/></div>)}<small>Edit amount or package macros for each food above. Totals are summed automatically; package values take priority over AI estimates. Changing portions recalculates meal totals.</small></section>}
 {(file||foods.length>0)&&<div className="analysis-box"><label className="field-block">Correct food or measured portions<input maxLength={600} value={details} disabled={locked} placeholder="e.g. paneer, not chicken; rice is 150g cooked" onChange={e=>setDetails(e.target.value)}/></label><label className="field-block">Add extras or hidden ingredients<input maxLength={600} value={extras} disabled={locked} placeholder="e.g. 1 tsp oil, 2 tbsp sauce, 1 banana" onChange={e=>setExtras(e.target.value)}/></label><div className="extras-chips">{['1 tsp oil','1 tsp ghee','1 tbsp sauce'].map(extra=><button type="button" disabled={locked} className="secondary" key={extra} onClick={()=>setExtras(v=>v?`${v}, ${extra}`:extra)}><Plus size={14}/>{extra}</button>)}</div><button type="button" className="primary" disabled={locked} onClick={()=>analyze()}><Sparkles size={17}/>{analyzing?'Analyzing…':foods.length?'Update estimate with changes':'Retry analysis'}</button><small>Free analysis has usage limits. Measured portions and readable labels improve estimates. Vitamins and minerals stay blank when unknown.</small></div>}
 {estimateNote&&<div className="notice estimate-note"><strong>Nutrition estimate · measured portions and labels improve it</strong><p>{estimateNote}</p></div>}
 {foods.length>0&&<label className="check-row portion-confirm"><input type="checkbox" disabled={locked} checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I reviewed the foods, portions, oils and sauces. These are estimates or values I supplied.</label>}<fieldset disabled={locked} className="meal-fields"><div className="form-grid"><label className="wide">Meal name<input required maxLength={120} value={form.name} placeholder="e.g. Dal, rice & vegetables" onChange={e=>update('name',e.target.value)}/></label><label>Meal type<select value={form.category} onChange={e=>update('category',e.target.value)}>{['Breakfast','Lunch','Dinner','Snack'].map(v=><option key={v}>{v}</option>)}</select></label><label>Date<input required type="date" value={form.date} onChange={e=>update('date',e.target.value)}/></label><label>Time<input required type="time" value={form.time} onChange={e=>update('time',e.target.value)}/></label></div><h3 className="form-section-title">Your meal totals</h3><div className="form-grid">{nutrientKeys.slice(0,5).map(k=><label key={k}>{labels[k]} ({unit(k)})<input required type="number" min={0} max={k==='calories'?20000:2000} step="0.1" value={form[k]} onChange={e=>update(k,e.target.value)}/></label>)}</div><details className="more-nutrients"><summary>Fats, sugar, vitamins & minerals (optional)</summary><p>Unknown values stay blank. Add values from a label or measured recipe.</p><div className="form-grid">{nutrientKeys.slice(5).map(k=><label key={k}>{labels[k]} ({unit(k)})<input type="number" min={0} max={100000} step="0.1" value={form[k]} onChange={e=>update(k,e.target.value)}/></label>)}</div></details><label className="field-block">Portions & notes<textarea value={form.notes} maxLength={1000} onChange={e=>update('notes',e.target.value)}/></label></fieldset>
 <div className="tool-actions"><button type="button" className="secondary" disabled={locked} onClick={()=>void keepAndClose()}>Keep draft & close</button><button type="button" className="text-btn" disabled={locked} onClick={async()=>{if(window.confirm('Discard this unfinished meal and its photo?')){draftPaused.current=true;await clearDraft(owner);reset();close();}}}>Discard draft</button></div>{onRecipe&&<button type="button" className="text-btn" disabled={locked} onClick={saveRecipe}>Save these totals as a recipe</button>}<div className="form-actions"><button type="button" className="secondary" disabled={locked} onClick={()=>setStage('capture')}>Choose another photo</button><button className="primary" type="submit" disabled={locked}>{busy?'Saving…':'Save meal to journal'}</button></div></form>}
 </DialogContent></Dialog>;
}



