'use client';
import {useState} from 'react';
import {BarcodeLookup} from './barcode-lookup';
import {Meal,Goals} from './model';
export function MealLibrary({meals,goals,repeat,removeTemplate}:{meals:Meal[];goals:Goals;repeat:(meal:Meal)=>void;removeTemplate:(id:string)=>void}){
 const [query,setQuery]=useState('');const matches=(name:string)=>name.toLowerCase().includes(query.trim().toLowerCase());
 const recent=meals.filter(m=>!m.demo).filter((meal,index,all)=>all.findIndex(other=>other.name===meal.name)===index).filter(m=>matches(m.name)).slice(0,6);
 return <section className="quick-log card"><div className="section-head"><div><div className="eyebrow">LESS TAPPING. MORE LIVING.</div><h2>Quick log</h2></div><span className="muted">EDIT BEFORE SAVING</span></div><p>Repeat a recent meal, favourite or recipe. Update portions and totals if today’s serving differs.</p><label className="library-search">Search your meals & recipes<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rice, oats, your saved recipes…"/></label><div className="quick-list">{goals.templates.filter(t=>matches(t.meal.name)).map(template=><div className="quick-item" key={template.id}><button onClick={()=>repeat({...template.meal,id:template.id})}><small>{template.kind}</small><strong>{template.meal.name}</strong><span>{Math.round(template.meal.calories)} kcal · {Math.round(template.meal.protein)}g protein</span></button><button className="icon-btn" aria-label={'Remove '+template.meal.name+' from saved meals'} onClick={()=>removeTemplate(template.id)}>×</button></div>)}{recent.map(meal=><div className="quick-item" key={meal.id}><button onClick={()=>repeat(meal)}><small>Recent meal</small><strong>{meal.name}</strong><span>{Math.round(meal.calories)} kcal · Tap to repeat</span></button></div>)}</div>{!recent.length&&!goals.templates.length&&<p className="fine-print">Your recent meals appear here. Open a saved meal to favourite it, or save a recipe from the meal form.</p>}<BarcodeLookup onMeal={repeat}/></section>;
}
