'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {Goals,dateKey,weightEntrySchema} from './model';
export function WeightTracker({goals,setGoals}:{goals:Goals;setGoals:(g:Goals)=>void}){
 const [date,setDate]=useState(dateKey()),[kg,setKg]=useState(String(goals.weight)),[busy,setBusy]=useState(false);
 const entries=[...goals.weights].sort((a,b)=>a.date.localeCompare(b.date)),recent=entries.slice(-7),mean=recent.length?recent.reduce((s,e)=>s+e.kg,0)/recent.length:null;
 async function save(){try{const entry=weightEntrySchema.parse({date,kg:Number(kg)});if(date>dateKey())throw Error('Choose today or an earlier date.');setBusy(true);const weights=[...entries.filter(e=>e.date!==date),entry].sort((a,b)=>a.date.localeCompare(b.date));if(weights.length>1000)throw Error('Export your history before adding more entries.');const latest=weights.at(-1)!;const response=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...goals,weights,weight:latest.kg})});const data=await response.json();if(!response.ok)throw Error(data.error||'Weight was not saved. Retry when connected.');setGoals(data.settings);toast.success('Weight entry saved.');}catch(e){toast.error(e instanceof Error?e.message:'Enter a valid date and weight.');}finally{setBusy(false);}}
 return <section className="card weight-card"><div className="section-head"><div><div className="eyebrow">PROGRESS OVER TIME</div><h2>Body-weight journal</h2></div><span className="muted">KG</span></div><p>Use comparable conditions when weighing. Short-term changes can reflect water and digestion.</p><div className="tool-actions"><label>Date<input type="date" max={dateKey()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Weight (kg)<input type="number" min="30" max="300" step="0.1" value={kg} onChange={e=>setKg(e.target.value)}/></label><button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save weight'}</button></div><div className="trend-grid"><div><small>Mean of latest {recent.length} entries</small><strong>{mean===null?'Not recorded':mean.toFixed(1)+' kg'}</strong><span>Entry average, not a daily average</span></div><div><small>Change since first entry</small><strong>{entries.length<2?'Not enough records':(entries.at(-1)!.kg-entries[0].kg).toFixed(1)+' kg'}</strong><span>{entries.length} dates recorded</span></div></div>{entries.length>0&&<details><summary>Recent weight entries</summary><ul className="weight-history">{entries.slice(-14).reverse().map(e=><li key={e.date}><span>{e.date}</span><strong>{e.kg} kg</strong></li>)}</ul></details>}<small>Entries are saved to your account. Saving the same date replaces that date’s entry.</small></section>;
}
