import {getChatGPTUser} from '../../chatgpt-auth';
import {createClient} from '../../../lib/supabase/server';
import {mealSchema} from '../../model';
const validId=(id:unknown):id is string=>typeof id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id);
const present=(row:any)=>({...JSON.parse(row.payload),id:row.id,photo:row.photo_key?'/api/photos/'+row.id:undefined});
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to load your meals.'},{status:401});try{const client=await createClient();const {data,error}=await client.from('meals').select('id,payload,photo_key').eq('owner',user.userId).order('date',{ascending:false}).order('id',{ascending:false}).limit(10000);if(error)throw error;return Response.json({meals:(data||[]).map(present)},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Your meals could not be loaded. Please try again.'},{status:503});}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to save your meal.'},{status:401});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});let photoKey:string|null=null;try{
 const form=await request.formData();if(form.get('owner')&&form.get('owner')!==user.userId)return Response.json({error:'Sign in to the account that saved this offline meal before syncing.'},{status:403});const parsed=mealSchema.safeParse(JSON.parse(String(form.get('meal'))));if(!parsed.success)return Response.json({error:parsed.error.issues[0].message},{status:400});
 const supplied=form.get('clientId');if(supplied&&!validId(supplied))return Response.json({error:'Invalid meal identifier'},{status:400});const id=supplied?String(supplied):crypto.randomUUID(),client=await createClient();
 const existing=await client.from('meals').select('id,payload,photo_key').eq('owner',user.userId).eq('id',id).maybeSingle();if(existing.error)throw existing.error;if(existing.data){if(existing.data.payload!==JSON.stringify(parsed.data))return Response.json({error:'This meal identifier was already used. Refresh and retry.'},{status:409});return Response.json({meal:present(existing.data)});}
 const photo=form.get('photo');if(photo instanceof File&&photo.size){if(photo.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(photo.type))return Response.json({error:'Choose a JPG, PNG or WebP photo under 5 MB.'},{status:400});photoKey=user.userId+'/'+id;const uploaded=await client.storage.from('meal-photos').upload(photoKey,photo,{contentType:photo.type,upsert:false});if(uploaded.error)throw uploaded.error;}
 const inserted=await client.from('meals').insert({id,owner:user.userId,date:parsed.data.date,payload:JSON.stringify(parsed.data),photo_key:photoKey});if(inserted.error){if(photoKey)await client.storage.from('meal-photos').remove([photoKey]);throw inserted.error;}
 return Response.json({meal:{...parsed.data,id,photo:photoKey?'/api/photos/'+id:undefined}},{status:201});
 }catch{return Response.json({error:'Your meal was not saved to the cloud. Please try again.'},{status:503});}}
export async function DELETE(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to delete a meal.'},{status:401});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});try{const {id}=await request.json();if(!validId(id))return Response.json({error:'Invalid meal identifier'},{status:400});const client=await createClient(),row=await client.from('meals').select('photo_key').eq('owner',user.userId).eq('id',id).maybeSingle();if(row.error)throw row.error;if(!row.data)return Response.json({error:'Meal not found'},{status:404});if(row.data.photo_key){const result=await client.storage.from('meal-photos').remove([row.data.photo_key]);if(result.error)throw result.error;}const result=await client.from('meals').delete().eq('owner',user.userId).eq('id',id);if(result.error)throw result.error;return Response.json({ok:true});}catch{return Response.json({error:'Meal could not be deleted. Please retry.'},{status:503});}}
